// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlYV1Zxp7uCCdNpz_dTJvaULvDmznSGAc',
    appId: '1:266842648861:web:5ffa54ea190b621240f1f4',
    messagingSenderId: '266842648861',
    projectId: 'kapout-f095f',
    authDomain: 'kapout-f095f.firebaseapp.com',
    storageBucket: 'kapout-f095f.appspot.com',
    measurementId: 'G-M9XZDXRWDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFJjhB4v7kJKO9jJqMiTCgC9fqlsdrTtg',
    appId: '1:266842648861:android:ae3e344e8f3d856240f1f4',
    messagingSenderId: '266842648861',
    projectId: 'kapout-f095f',
    storageBucket: 'kapout-f095f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQwBH9tKlj_6xnzakLy_XNw9y85AAeH-s',
    appId: '1:266842648861:ios:f1e99992cfa1659640f1f4',
    messagingSenderId: '266842648861',
    projectId: 'kapout-f095f',
    storageBucket: 'kapout-f095f.appspot.com',
    iosBundleId: 'com.example.kapout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQwBH9tKlj_6xnzakLy_XNw9y85AAeH-s',
    appId: '1:266842648861:ios:f1e99992cfa1659640f1f4',
    messagingSenderId: '266842648861',
    projectId: 'kapout-f095f',
    storageBucket: 'kapout-f095f.appspot.com',
    iosBundleId: 'com.example.kapout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlYV1Zxp7uCCdNpz_dTJvaULvDmznSGAc',
    appId: '1:266842648861:web:8e1244eab1a49a2240f1f4',
    messagingSenderId: '266842648861',
    projectId: 'kapout-f095f',
    authDomain: 'kapout-f095f.firebaseapp.com',
    storageBucket: 'kapout-f095f.appspot.com',
    measurementId: 'G-LFFYC6DZ4H',
  );
}
